---
name: CI
"on": [push, pull_request]

env:
  ZIG_VERSION: 0.16.0

jobs:
  test-linux:
    name: Test
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libdbus-1-dev

      - name: Run tests
        run: |
          dbus-run-session -- zig build test --verbose --summary all

  demo-linux:
    name: Demo | ${{ matrix.mode }}
    runs-on: codeberg-medium
    strategy:
      fail-fast: false
      matrix:
        mode: ["fast", "safe", "small", "off"]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libdbus-1-dev

      - name: Build demo
        run: |
          zig build demo --release=${{ matrix.mode }} --verbose --summary all

  lint:
    name: Format
    runs-on: codeberg-tiny
    if: forgejo.ref_type != 'tag'

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Check formatting
        run: zig fmt --check .

  release:
    name: Create release
    needs: ["test-linux", "demo-linux"]
    if: >-
      forgejo.ref_type == 'tag' &&
      forgejo.repository_owner == 'charlesrocket'

    uses: charlesrocket/reusable/.forgejo/workflows/release.yml@trunk
    with:
      skip-assets: true
